"""CyberLens 2.0 - SIH-specific features: demo scenario loader and summary generator."""

import datetime
import streamlit as st

from risk_engine import total_exposure, compute_overall_cr_i

DEMO_SCENARIO = {
    "UPI_SWITCH_001": ["V_UPI_001", "V_UPI_002"],
    "CBS_SERVER_001": ["V_CBS_001", "V_CBS_002"],
    "MOBILE_BANKING_001": ["V_MOBILE_001"],
    "API_GATEWAY_001": ["V_API_001", "V_API_002"],
    "AUTH_SERVER_001": ["V_AUTH_001"],
}


def load_demo_scenario(session):
    """Filter the session's vulns_by_asset to the high-risk UPI Switch scenario."""
    # Audit: log scenario load action
    audit = session.get("audit_log", [])
    audit.append({"action": "load_demo_scenario", "timestamp": __import__("time").time()})
    session["audit_log"] = audit[:1000]

    import data_loader
    all_assets = data_loader.get_assets()
    all_vulns = {a["asset_id"]: data_loader.get_vulnerabilities(a["asset_id"]) for a in all_assets}

    selected = {
        asset_id: [v for v in vulns if v["vuln_id"] in DEMO_SCENARIO.get(asset_id, [])]
        for asset_id, vulns in all_vulns.items()
        if asset_id in DEMO_SCENARIO
    }
    session["vulns_by_asset"] = {k: v for k, v in selected.items() if v}
    session["assets"] = [a for a in all_assets if a["asset_id"] in selected]
    # Trigger risk matrix recompute
    from risk_engine import compute_risk_matrix
    session["risk_matrix"] = compute_risk_matrix(
        session["assets"], session["vulns_by_asset"]
    )
    st.success("Loaded UPI Switch Demo Scenario (high-risk subset: 5 assets, 8 vulnerabilities).")


def reset_full_portfolio(session):
    """Restore the full dataset from data_loader."""
    import data_loader
    from risk_engine import compute_risk_matrix
    from controls_library import CONTROLS
    assets = data_loader.get_assets()
    vulns_by_asset = {a["asset_id"]: data_loader.get_vulnerabilities(a["asset_id"]) for a in assets}
    risk_matrix = compute_risk_matrix(assets, vulns_by_asset)
    session["assets"] = assets
    session["vulns_by_asset"] = vulns_by_asset
    session["risk_matrix"] = risk_matrix
    session["controls"] = list(CONTROLS.values())
    st.success("Reset to full portfolio (10 assets, 17 vulnerabilities).")


def generate_sih_summary(session):
    """Write SIH_Submission.md with key metrics and impact framing."""
    assets = session["assets"]
    vulns_by_asset = session["vulns_by_asset"]
    exposure = total_exposure(assets, vulns_by_asset)
    cr_i = compute_overall_cr_i(assets, vulns_by_asset)
    num_vulns = sum(len(v) for v in vulns_by_asset.values())
    users_impacted = sum(a["daily_transaction_volume"] for a in assets)
    # MGNREGA-day equivalence: ~₹266/day wage (typical)
    mgnrega_days = int(exposure / 266) if exposure > 0 else 0

    content = f"""# Smart India Hackathon 2024 — CyberLens 2.0 Submission

## 1. Problem Statement
India's digital financial infrastructure processes over 350 million UPI
transactions daily (~₹3.5 lakh crore). Existing cyber-risk tools give
qualitative scores (Low/Medium/High) that do not translate into financial
impact or actionable budget decisions. RBI, SEBI, and NPCI require
quantifiable risk exposure in monetary terms for effective governance and
budget allocation.

## 2. Solution Overview
CyberLens 2.0 is an AI-enhanced Cyber Risk Quantification Platform that
transforms raw vulnerability, asset, and transaction data into RBI-aligned
financial risk metrics (in ₹) and produces an AI-optimized investment plan
that maximizes risk reduction per rupee spent.

## 3. Impact Metrics
- **Estimated Annual Risk Exposure:** ₹{exposure:,.0f}
- **Assets under assessment:** {len(assets)}
- **Vulnerabilities quantified:** {num_vulns}
- **Daily transactions represented:** {users_impacted:,}
- **Cyber Resilience Index (CR-I):** {cr_i:.1f}/100
- **MGNREGA-day equivalence:** {mgnrega_days:,} days of rural wage protected

## 4. Technical Stack
- **Frontend:** Streamlit (Executive + Technical dashboards)
- **Engine:** Python 3.11 — RBI-weighted CVSS, CR-I, EAL, ROSI knapsack optimizer
- **Data:** SQLite + sample CSV (zero-setup demo)
- **AI:** Few-shot remediation templates (Hindi/English), LLM-ready fallback

## 5. Compliance Alignment
Every vulnerability is auto-mapped to its exact regulatory clause (e.g.,
RBI/2023-24/105.A.3 for MFA requirements), enabling governance teams to
audit and prioritize by mandate.

## 6. Future Scope
- Real-time CERT-In/NVD vulnerability feeds
- XGBoost-based scoring replacement for the rule-based model
- Exact integer optimization via PuLP
- Multi-language support (regional Indian languages)
- Kubernetes-ready micro-services deployment

## 7. Open-Source Pledge
Released under AGPL-3 to enable community audit and adoption by India's
public-sector banks and payment systems.
---
*Generated by CyberLens 2.0 on {datetime.date.today().isoformat()}.*
"""
    # Audit: log summary generation
    audit = session.get("audit_log", [])
    audit.append({"action": "generate_sih_summary", "timestamp": __import__("time").time(), "file": "SIH_Submission.md"})
    session["audit_log"] = audit[:1000]
    with open("SIH_Submission.md", "w", encoding="utf-8") as f:
        f.write(content)
    st.success("Generated `SIH_Submission.md` — ready for SIH portal upload.")
    st.download_button(
        label="📥 Download SIH_Submission.md",
        data=content,
        file_name="SIH_Submission.md",
        mime="text/markdown",
    )